-- Insert mock data for credit notes
-- Run this in Supabase SQL Editor

-- Insert mock credit notes with correct column structure
INSERT INTO public.credit_notes (
  credit_note_number,
  customer_id,
  credit_date,
  reason,
  reason_description,
  status,
  approval_required,
  subtotal,
  tax_amount,
  discount_amount,
  total_amount,
  refund_method,
  affects_inventory,
  notes,
  created_by
) VALUES
(
  'CN-0001',
  (SELECT id FROM public.customers WHERE name = 'Retail Store ABC' LIMIT 1),
  '2024-01-15',
  'damage',
  'Items returned due to damage during shipping',
  'approved',
  false,
  500.00,
  50.00,
  0.00,
  550.00,
  'credit_account',
  true,
  'Customer returned damaged goods - shipping damage confirmed',
  (SELECT id FROM public.profiles WHERE role_id = (SELECT id FROM public.roles WHERE name = 'admin') LIMIT 1)
),
(
  'CN-0002',
  (SELECT id FROM public.customers WHERE name = 'Wholesale Distributor XYZ' LIMIT 1),
  '2024-01-20',
  'billing_error',
  'Wrong items were shipped and billed',
  'processed',
  false,
  200.00,
  20.00,
  10.00,
  210.00,
  'bank_transfer',
  true,
  'Incorrect items were shipped - customer requested refund',
  (SELECT id FROM public.profiles WHERE role_id = (SELECT id FROM public.roles WHERE name = 'admin') LIMIT 1)
),
(
  'CN-0003',
  (SELECT id FROM public.customers WHERE name = 'Online Shop Express' LIMIT 1),
  '2024-01-25',
  'cancellation',
  'Order cancelled by customer before shipping',
  'pending',
  true,
  120.00,
  12.00,
  0.00,
  132.00,
  'credit_account',
  false,
  'Order cancelled by customer - no inventory impact',
  (SELECT id FROM public.profiles WHERE role_id = (SELECT id FROM public.roles WHERE name = 'admin') LIMIT 1)
),
(
  'CN-0004',
  (SELECT id FROM public.customers WHERE name = 'Regional Distributor North' LIMIT 1),
  '2024-01-28',
  'damage',
  'Quality control issues identified in batch',
  'approved',
  false,
  800.00,
  80.00,
  10.00,
  870.00,
  'store_credit',
  true,
  'Quality control issues identified - batch recall',
  (SELECT id FROM public.profiles WHERE role_id = (SELECT id FROM public.roles WHERE name = 'admin') LIMIT 1)
),
(
  'CN-0005',
  (SELECT id FROM public.customers WHERE name = 'Local Business Solutions' LIMIT 1),
  '2024-01-30',
  'billing_error',
  'Incorrect pricing applied to order',
  'processed',
  false,
  75.00,
  7.50,
  7.00,
  75.50,
  'cash',
  false,
  'Pricing error corrected - customer overcharged',
  (SELECT id FROM public.profiles WHERE role_id = (SELECT id FROM public.roles WHERE name = 'admin') LIMIT 1)
)
ON CONFLICT (credit_note_number) DO NOTHING; 