services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEBUG=false
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: versal-net
