-- Enable Row Level Security (RLS) for warehouse module tables
ALTER TABLE delivery_challan_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_challans ENABLE ROW LEVEL SECURITY;
ALTER TABLE pick_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pick_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_indent_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_indents ENABLE ROW LEVEL SECURITY;
ALTER TABLE put_away_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE put_aways ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_check_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_delivery_challan_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_delivery_challans ENABLE ROW LEVEL SECURITY;
